# Site settings
title: Thomas' projects
email: thomas.tanay.13@ucl.ac.uk
description: > # this means to ignore newlines until "baseurl:"
  I archive here some of the projects I have been working on in my postgraduate time.
baseurl:  # the subpath of your site, e.g. /blog/
url:  # the base hostname & protocol for your site
twitter_username: Thomas_Tanay
github_username:  thomas-tanay

# Build settings
markdown: kramdown

highlighter: rouge

# Pagination
paginate: 15
paginate_path: "/blog/page:num/"